declare namespace NodeJS {
  interface ProcessEnv {
    API_BASE_URL?: string;
    EXPO_PUBLIC_API_BASE_URL?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_IOS_API_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_BRAIN_PRODUCT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_PRO_PRODUCT_ID?: string;
    REVENUECAT_IOS_KEY?: string;
    REVENUECAT_ANDROID_KEY?: string;
  }
}
